### PR TITLE
Added Typescript casting support for `oneOfType`

### PR DESCRIPTION
**Pull request by victorgarciaesgi**
This PR is targeted for `oneOfType`.

## Problem before:

*Before vue-types*

```ts
props: {
   foo: { type: [String, Object] as PropType<RawLocation> }
}
```

*With vue-types ☹️*

image

## With these changes, we can now cast the type we want and still have the default behaviour!

```ts
type RawLocation = string | { name: string }
const ctor = oneOfType([String, Object]) // Valid
const route = oneOfType<RawLocation>([String, Object]) // Valid
```

Screenshot at Jul 12 21-00-15
Screenshot at Jul 12 21-00-28

### CODE REVIEW

**Comment by victorgarciaesgi** [comment]
Also worth notting, it could be better if `U` and `V` could still be infered to check the liability of the casting,  but Typescript is blocking us since 2016 https://github.com/microsoft/TypeScript/issues/10571 😩

**Comment by dwightjack** [comment]
Thanks!

I've changed the base branch to `ts-args-for-natives` so that I can merge it and add the related documentation.

**Comment by dwightjack** [comment]
@victorgarciaesgi Sorry for commenting on a closed PR.

After merging I found that these changes create some type issues with the `.def()` method:

```ts
const ctor = oneOfType([String, Object]) // Valid
ctor.def('hello') // Argument of type 'string' is not assignable to parameter of type 'StringConstructor | ObjectConstructor'
```

Any hint on how to fix it?

**Comment by victorgarciaesgi** [comment]
@dwightjack Oh shit sorry I will look at it right now!

**Comment by victorgarciaesgi** [comment]
@dwightjack I fixed it on this branch

**Comment by victorgarciaesgi** [comment]
Do you want me to make another PR?

**Pull request merged**
