### PR TITLE
Add generic TS argument to validators + example refactoring

### LINKED ISSUE #134: Support for Typescript casting in `string` validator
Hi and thanks for the 4.0 version! This is really time saving.

I found out that Typescript support has landed and made me use it! 
As i'm rewriting my component props (By the way, it's not very clear in the docs how to cast a type on a validator: `object<User>()`), I found out that `string()` does not support casting and that's a bummer because it is really usefull in a lot of cases!

Ex Before vue-types

```ts
export enum PopinAlignement {
  Center = 'Center',
  Start = 'Start',
  ContainerStart = 'ContainerStart',
  ContainerEnd = 'ContainerEnd',
  End = 'End',
  Full = 'Full',
}

export default defineComponent({
  props: {
     alignement: { type: String as PropType<PopinAlignement> },
  }
})
```

With vue-types

```ts
export default defineComponent({
  props: {
     // Error :(
     alignement: string<PopinAlignement>(),
  }
})
```

In vue-types, I can only type this as `String` and not an enum or a literal type like `type size = 'sm' | 'md'`

### LINKED ISSUE #140: `oneOfType([Array, any()])` throws error at prop validation
Hi it's me again! :D 

I'm translating all my props to vue-types, and came accross a bug with `oneOfType`.

Before:

```ts
props: {
 value: { type: [Array, null] as PropType<any | any[]> }
}
```

So in `vue-types`:

```ts
props: {
 value: oneOfType([Array, any()])
}
```

And I got this errors :(

image

### PR DESCRIPTION
**Pull request by dwightjack**
Closes #140 
Closes #134

This PR iterates over #135 and #138:
- allow type constraint to `number()` and `integer()` validators
- allow type constraint to `any()` validator
- update documentation

It also includes some refactoring to the `examples` folder. Now it uses Vite for faster compilation.

A demo version has been published as `vue-types@4.1.0-beta.2`.

### CODE REVIEW

**Comment by dwightjack** [comment]
@victorgarciaesgi I have added a generic type argument to `any()` as well.

About the documentation: As before, there are TS hints info-boxes throughout the documentation. Anyway, I added a dedicated page for TypeScript usage that collects all the information to make them more prominent.

It looks like GitHub Pages does not have a branch preview feature, but you can check out the markdown source here: https://github.com/dwightjack/vue-types/blob/e5eb45a512c17742a55a1cf8daedccb6ff2e4b5a/docs/advanced/typescript.md

PS: I've published the changes in `vue-types@4.1.0-beta.2`.

**Comment by victorgarciaesgi** [comment]
Ok thanks! I will test the beta :)

**Comment by victorgarciaesgi** [comment]
@dwightjack Nothing To report for now it works great :D 

image

**Comment by dwightjack** [comment]
Merging this into `next` branch. I need some more work done before releasing v4.1.0  (see https://github.com/dwightjack/vue-types/milestone/4)

**Pull request merged**
